FROM python:3.12-slim

WORKDIR /app

COPY dashboard/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY dashboard/ .

EXPOSE 8501

CMD streamlit run streamlit_app.py --server.address=0.0.0.0 --server.port=${PORT:-8501}