"""remove old sensor fields

Revision ID: 527ce2bc57a1
Revises: 0771e71d429d
Create Date: 2026-07-24 14:17:44.436989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527ce2bc57a1'
down_revision: Union[str, Sequence[str], None] = '0771e71d429d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Remove old sensor fields
    op.drop_column(
        'sensor_readings',
        'pressure'
    )

    op.drop_column(
        'sensor_readings',
        'vibration'
    )

    op.drop_column(
        'sensor_readings',
        'temperature'
    )

    # Make AI4I fields required
    op.alter_column(
        'sensor_readings',
        'air_temperature',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False
    )

    op.alter_column(
        'sensor_readings',
        'process_temperature',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False
    )

    op.alter_column(
        'sensor_readings',
        'rotational_speed',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False
    )

    op.alter_column(
        'sensor_readings',
        'torque',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False
    )

    op.alter_column(
        'sensor_readings',
        'tool_wear',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sensor_readings', sa.Column('vibration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sensor_readings', sa.Column('pressure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('sensor_readings', 'tool_wear',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensor_readings', 'torque',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensor_readings', 'rotational_speed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensor_readings', 'process_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sensor_readings', 'air_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
