"""add failure label to sensor readings

Revision ID: 7f91dcb2c58c
Revises: a71d2f7bbd11
Create Date: 2026-07-22 16:12:53.974437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f91dcb2c58c'
down_revision: Union[str, Sequence[str], None] = 'a71d2f7bbd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.add_column('sensor_readings', sa.Column('failure', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'failure')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    # ### end Alembic commands ###
